Added ops script and common functions.
Added few common functions such as ping, ssh, and others
as well as an ops script to be used as an index of operations
to run agains list of systems (bulk ops).

diff --git a/common_functions b/common_functions
--- a/common_functions
+++ b/common_functions
@@ -16,11 +16,22 @@ _PROXY=''
 _DOMAIN=',.intel.com'
 _PACKAGE_MANAGER='apt'
 _INSTALLER_CMD='apt-get install -y'
+_SSH_CMD=''
 #=================================================
 # GLOBAL FUNCTIONS
 #=================================================
 
 function AddUser {
+: 'Adds a user to system [Ubuntu or Centos]. Password disabled.
+ Positional arguments:
+ 1: Username
+ 2: Password
+ Optional arguments:
+ 3: sudoer
+    Defaults to True
+      If True - User is added to the sudoers group
+      If False - User is not within sudoers
+'
     AddUser"${_PACKAGE_MANAGER}" $@
 }
 
@@ -53,6 +64,152 @@ function AddUseryum {
             echo "Added user ${1}. Belogs to sudoers group".
         fi
     fi
+}
+
+function CheckBios {
+: 'Check that system Bios version contains a given version pattern - via OS.
+ [CentOS7.4 or WindowsServer2016]
+ Positional parameters:
+ 1: SystemName or IP to ssh into it.
+ 2: User to authenticate.
+ 3: Password to authenticate.
+ Note: If user/password fail, will try default ssh-keys.
+'
+  sy="${1}"; user="${2}"; passw="${3}"
+  CheckSsh $sy $user $passw 'False'
+  [[ $_SSH_CMD == 'error' ]] && continue
+
+  # Check BIOS
+  $_SSH_CMD -q $user@$sy "uname" &>result
+  if [[ $( cat result ) == 'Linux' ]]; then
+    # if Linux
+    cv=$( $_SSH_CMD $user@$sy "dmidecode --type 0|grep Version|sed 's/.*Version:.//g'" )
+  else
+    # if Windows
+    cv=$( $_SSH_CMD $user@$sy "powershell; systeminfo | FINDSTR ^BIOS.Version" )
+  fi
+  rm -f result
+  msg=" - $sy BIOS -"
+  msg1="- Expected Version: $_BIOSVER, Current Version: $cv"
+  [[ $cv =~ $_BIOSVER ]] && echo "$msg MATCHES" || echo "$msg NOT MATCH $msg1"
+}
+
+function CheckPing {
+: 'Pings a system - Prints only one line to indicate either success or failure.
+ Positional arguments:
+ 1: SystemName or IP to ping.
+ Optional arguments:
+ 2: verbose
+    Defaults to True.
+      If True - Prints success or failure message.
+      If False - Prints only failure message (if any), supress success message
+      If Raw - Prints the ping output as-is
+ NOTE: SEE ALSO WaitForPing FUNCTION
+'
+  sy="${1}"; verbose="${2:-True}"
+
+  result=$( ping -c 1 $sy )
+
+  [[ $verbose == Raw ]] && echo $result && continue
+
+  _reg='Destination Host Unreachable'
+  msgS=" - $sy - Successful Ping"
+  msgF=" - $sy - Failed Ping - Host Unreachable \n $result"
+  [[ $result =~ $_reg ]] && echo -e "$msgF" || [[ $verbose == True ]] && echo $msgS
+}
+
+function CheckSsh {
+: 'Verify system connection via ssh - etiher with user/ password or ssh-keys
+ [CentOS7.4 or WindowsServer2016]
+ Positional arguments:
+ 1: SystemName or IP to ssh into.
+ 2: User to authenticate.
+ 3: Password to authenticate.
+ Optional arguments:
+ 4: verbose
+    Defaults to True.
+      If True - Prints success or failure message.
+      If False - Prints only failure message (if any), supress success message
+ Note: If user/password fail, will try default ssh-keys.
+'
+  sy="${1}"; user="${2}"; passw="${3}"; verbose="${4:-True}"
+  # Check we can ssh - with user-password else try sshkeys
+  _SSH_CMD="sshpass -p $passw ssh"
+  sshpass -p $passw ssh $user@$sy "exit"
+  if [[ $? -ne 0 ]]; then
+    _SSH_CMD='ssh'
+    ssh -o preferredAuthentications=publickey -q $user@$sy "exit"
+    [[ $? -ne 0 ]] && echo -e "ERROR: UNABLE TO SSH $sy.\n" && _SSH_CMD='error'
+  fi
+  [[ $_SSH_CMD != 'error' && $verbose == 'True' ]] && echo " - $sy - Able to ssh"
+}
+
+function CheckVmm {
+: 'Prints current available VMs details to validate its status.
+[CentOS7.4 or windowsServer2016]
+   For linux - Done via virsh
+ Positional arguments:
+ 1: SystemName or IP to ssh into.
+ 2: User to authenticate.
+ 3: Password to authenticate.
+ Note: If user/password fail, will try default ssh-keys.
+'
+  sy="${1}"; user="${2}"; passw="${3}"
+  CheckSsh $sy $user $passw 'False'
+  [[ $_SSH_CMD == 'error' ]] && continue
+
+  # Check vmm
+  echo -e "\n\n - $sy - Reviewing VMs on system."
+  $_SSH_CMD -q $user@$sy "uname" &>result
+
+  if [[ $( cat result ) == 'Linux' ]]; then
+    # IF LINUX SYSTEM
+    # Print current VMs on the host
+    vmms=$( $_SSH_CMD $user@$sy "virsh list --all" )
+    echo "$vmms"
+    [[ $vmms =~ "off" ]] && echo " - $sy - Error: something went wrong."
+  else
+    # IF WINDOWS SYSTEM
+    # Print current VMs on the host
+    $_SSH_CMD $user@$sy "powershell; get-vm"
+    $_SSH_CMD $user@$sy 'powershell; if(Select-String -Path c:/vms/vm_status.log -Pattern "heartbeat.failure") { exit 1 }; exit'
+    # On failure get vm_status.log file
+    if [[ $? -ne 0 ]]; then
+      fname="./${sy}.vm_status_$(date '+%Y_%m_%d_%H:%M:%S').log"
+      echo " - $sy - Error: vm_status.log - HAVE HEARBEAT FAILURES"
+      echo "Collecting file into $fname"
+      sshpass -p $passw scp $user@$sy:C:/vms/vm_status.log ${fname}
+    fi
+  fi
+  rm -f result
+}
+
+function CheckVtx {
+: 'Verifies system has Intel Virtual Technology enabled (aka vtx)
+TODO: Check also for vtd (direct I/O) via OS
+[CentOS7.4 or windowsServer2016]
+ Positional arguments:
+ 1: SystemName or IP to ping.
+ 2: User to authenticate.
+ 3: Password to authenticate.
+ Note: If user/password fail, will try default ssh-keys.
+'
+  sy="${1}"; user="${2}"; passw="${3}"
+  CheckSsh $sy $user $passw 'False'
+  [[ $_SSH_CMD == 'error' ]] && continue
+
+  # Check Virtualization
+  $_SSH_CMD -q $user@$sy "uname" &>result
+  if [[ $( cat result ) == 'Linux' ]]; then
+    # if Linux
+    $_SSH_CMD $user@$sy "[[ -c '/dev/kvm' ]] && exit || exit 1"
+  else
+    # if Windows - Ensure hyperV reqs are met
+    $_SSH_CMD $user@$sy 'powershell; "if(systeminfo | FINDSTR ^Hyper-V* | FINDSTR .*No) { exit 1 }; exit"'
+  fi
+  rm -f result
+  msg=" - $sy - VTX"
+  [[ $? -eq 0 ]]  && echo "$msg ENABLED" || echo "$msg NOT ENABLED"
 }
 
 function EnsureNonRoot {
@@ -107,6 +264,10 @@ function IsXenial {
 }
 
 function PrintError {
+:'Prints a given message as an error and quit execution
+  Positional Arguments:
+  1: Error message to be printed.
+'
     echo "************************" >&2
     echo "* $(date +"%F %T.%N") ERROR: $1" >&2
     echo "************************" >&2
@@ -114,6 +275,12 @@ function PrintError {
 }
 
 function PrintHelp {
+:'Prints the Help for a commands.
+ Positional Arguments:
+ 1. A description of script functionallity.
+ 2: The name of the script.
+ 3: String with additional script options help
+'
     echo " "
     echo "Script: $1. Optionally uses given proxy"
     echo " "
@@ -148,6 +315,11 @@ function SetFirewallUFW {
 }
 
 function SetKeyPair {
+: 'Creates a key-pair unattended for root or other user
+ Optional arguments:
+ 1: userName
+    Defaults to root user.
+'
     [[ -n $1 ]] && path="/home/$1" || path='/root'
     mkdir -p $path
     ssh-keygen -q -t rsa -b 4096 -C 'dlux keypair' -N "" -f "$path/.ssh/id_rsa"
@@ -155,7 +327,11 @@ function SetKeyPair {
 }
 
 function SetLocale {
-    # Set locale
+:' Sets locale to US.
+ Positional arguments:
+ 1: Home directory to be exported.
+'
+    Set locale
     locale-gen en_US
     update-locale
     export HOME=$1
@@ -192,6 +368,10 @@ function SetPackageManager {
 }
 
 function SetProxy {
+: 'Sets a proxy for package manager and as envVar
+ Positional arguments:
+ 1: Proxy - sintasix http://server:port
+'
     if [[ -z "${1}" || "${1}" == -* ]]; then
         PrintError "Function set_proxy - Missing proxy data."
     fi
